services:
  - type: web
    name: for-kavya
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: kavya-db
          property: connectionString

databases:
  - name: kavya-db
    plan: free
